version: "3.8"

services:
  vulnapp:
    build: ./vulnapp
    container_name: vulnapp
    ports:
      - "5001:5000"   # acceso en host:5001 -> contenedor:5000
    restart: unless-stopped

  fixedapp:
    build: ./fixedapp
    container_name: fixedapp
    ports:
      - "5002:5000"   # acceso en host:5002 -> contenedor:5000
    restart: unless-stopped
